include: project-template.yml

name: Events

options:
  bundleIdPrefix: mx.metalluxxproject
  deploymentTarget:
    iOS: "13.0"
  transitivelyLinkDependencies: true
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "5.3.2"

targets:
  Application:
    templates: [Application, ApplicationSwiftLint, Rx]
    sources: 
      - path: Application/Source
        type: Folder
      - path: Application/Resource
        excludes:
          - Info.plist
        type: Folder
    info:
      path: Application/Resource/Info.plist
      properties:
        CFBundleDisplayName: Events
        NSAppTransportSecurity: { NSAllowsArbitraryLoads: true }
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        TARGET_PATH: Application
        TARGETED_DEVICE_FAMILY: 1

    dependencies:
      - target: AppFoundation
      - target: NewNetworking
      - target: AuthScreen
      - target: Platform
      - framework: Carthage/Build/Kingfisher.xcframework
      - framework: Carthage/Build/Overture.xcframework
      - framework: Carthage/Build/KeychainAccess.xcframework

  AppFoundation:
    templates: [Framework, SwiftLint]
    dependencies: 
      - framework: Carthage/Build/Kingfisher.xcframework
      - framework: Carthage/Build/Overture.xcframework
      - framework: Carthage/Build/KeychainAccess.xcframework
      
  NewNetworking:
    templates: [Rx, Framework, SwiftLint]

  Platform:
    templates: [Rx, Framework, SwiftLint]
    dependencies:
      - target: NewNetworking
      - target: AppFoundation

  AuthScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    dependencies:
      - target: EventsScreen
      - target: RegistrationScreen
      - target: SettingsScreen

  RegistrationScreen:
    templates: [ScreenFramework, Rx, SwiftLint]

  NewsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]

  SettingsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]

  EventsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    scheme:
      testTargets:
        - EventsScreenTests
    dependencies: 
      - target: Services
      - target: NewsScreen

  EventsScreenTests:
    templates: [TestFramework, FileResouces]

  DesignEngine:
    templates: [Framework, SwiftLint]
    dependencies:
      - framework: Carthage/Build/Kingfisher.xcframework 

  Services:
    templates: [Rx, Framework, SwiftLint]
    dependencies:
      - target: NewNetworking 
