include: project-template.yml

name: Events

options:
  bundleIdPrefix: com.skw883halhag2.kh82hk
  deploymentTarget:
    iOS: "13.0"
  transitivelyLinkDependencies: true
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "5.3.2"

targets:
  Application:
    templates: [Application, ApplicationSwiftLint, Rx]
    sources: 
      - path: Application/Source
        type: Folder
      - path: Application/Resource
        excludes:
          - Info.plist
        type: Folder
    info:
      path: Application/Resource/Info.plist
      properties:
        CFBundleDisplayName: Events
        NSAppTransportSecurity: { NSAllowsArbitraryLoads: true }
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: N3394Z6629
        CODE_SIGN_IDENTITY: iPhone Developer
        PROVISIONING_PROFILE_SPECIFIER: 
        TARGET_PATH: Application
        TARGETED_DEVICE_FAMILY: 1

    dependencies:
      - target: Library
      - target: NewNetworking
      - target: AuthScreen
      - target: Platform
      - carthage: Kingfisher
      - carthage: Overture
      - carthage: KeychainAccess

  Library:
    templates: [Framework, SwiftLint]
    dependencies: 
      - carthage: Kingfisher
      - carthage: Overture
      - carthage: KeychainAccess
      
  NewNetworking:
    templates: [Rx, Framework, SwiftLint]

  Platform:
    templates: [Rx, Framework, SwiftLint]
    dependencies:
      - target: NewNetworking

  AuthScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    dependencies:
      - target: EventsScreen
      - target: RegistrationScreen
      - target: SettingsScreen

  RegistrationScreen:
    templates: [ScreenFramework, Rx, SwiftLint]

  NewsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]

  SettingsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]

  EventsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    scheme:
      testTargets:
        - EventsScreenTests
    dependencies: 
      - target: Services
      - target: NewsScreen

  EventsScreenTests:
    templates: [TestFramework, FileResouces]

  DesignEngine:
    templates: [Framework, SwiftLint]
    dependencies:
      - carthage: Kingfisher 

  Services:
    templates: [Rx, Framework, SwiftLint]
    dependencies:
      - target: NewNetworking 
