include: project-template.yml

name: Events

options:
  bundleIdPrefix: com.skw883halhag2.kh82hk
  deploymentTarget:
    iOS: "13.0"
  transitivelyLinkDependencies: true
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "5.3.2"

targets:
  Application:
    # directlyEmbedCarthageDependencies: true
    templates: [Application, SwiftLint]
    sources: 
      - path: Application/Source
        type: Folder
      - path: Application/Resource
        excludes:
          - Info.plist
        type: Folder
    info:
      path: Application/Resource/Info.plist
      properties:
        CFBundleDisplayName: Events
        NSAppTransportSecurity: { NSAllowsArbitraryLoads: true }
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: N3394Z6629
        CODE_SIGN_IDENTITY: iPhone Developer
        PROVISIONING_PROFILE_SPECIFIER: 
        TARGET_PATH: Application
        TARGETED_DEVICE_FAMILY: 1

    dependencies:
      - target: Library
      - target: NewNetworking
      - target: AuthScreen
      - target: Platform
      - carthage: Kingfisher
      - carthage: Overture
      - carthage: KeychainAccess

  Library:
    templates: [Framework, SwiftLint]
    info:
      path: Library/Resource/Info.plist
    settings: 
      base: 
        TARGET_PATH: Library
    sources: Library/Source
    dependencies: 
      - carthage: Kingfisher
      - carthage: Overture
      - carthage: KeychainAccess
      
  NewNetworking:
    templates: [Rx, Framework, SwiftLint]
    info:
      path: NewNetworking/Resources/Info.plist
    settings: 
      base: 
        TARGET_PATH: NewNetworking
    sources: NewNetworking/Sources

  Platform:
    templates: [Rx, Framework, SwiftLint]
    info:
      path: Platform/Resources/Info.plist
    settings:
      base:
        TARGET_PATH: Platform
    sources: Platform/Sources

  AuthScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    info:
      path: AuthScreen/Resources/Info.plist
    settings:
      base:
        TARGET_PATH: AuthScreen
    sources: AuthScreen/Sources
    dependencies:
      - target: EventsScreen
      - target: RegistrationScreen

  RegistrationScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    info:
      path: RegistrationScreen/Resources/Info.plist
    settings:
      base:
        TARGET_PATH: RegistrationScreen
    sources: RegistrationScreen/Sources

  NewsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    info:
      path: NewsScreen/Resources/Info.plist
    settings:
      base:
        TARGET_PATH: NewsScreen
    sources: NewsScreen/Sources

  SettingsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    info:
      path: SettingsScreen/Resources/Info.plist
    settings:
      base:
        TARGET_PATH: SettingsScreen
    sources: SettingsScreen/Sources

  EventsScreen:
    templates: [ScreenFramework, Rx, SwiftLint]
    info:
      path: EventsScreen/Resources/Info.plist
    settings:
      base:
        TARGET_PATH: EventsScreen
    sources: EventsScreen/Sources
    dependencies: 
      - target: NewNetworking
      - target: NewsScreen

  DesignEngine:
    templates: [Framework, SwiftLint]
    info:
      path: DesignEngine/Resources/Info.plist
    settings:
      base:
        TARGET_PATH: DesignEngine
    sources: DesignEngine/Sources
    dependencies:
      - carthage: Kingfisher 