include: project-template.yml

name: Events

options:
  bundleIdPrefix: com.skw883halhag2.kh82hk
  deploymentTarget:
    iOS: "13.0"
  transitivelyLinkDependencies: true
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "5.1.2"

targets:
  Application:
    # directlyEmbedCarthageDependencies: true
    templates: [Application]
    sources: 
      - path: Application/Source
        type: Folder
      - path: Application/Resource
        excludes:
          - Info.plist
        type: Folder
    info:
      path: Application/Resource/Info.plist
      properties:
        CFBundleDisplayName: Events
        NSAppTransportSecurity: { NSAllowsArbitraryLoads: true }
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: N3394Z6629
        CODE_SIGN_IDENTITY: iPhone Developer
        PROVISIONING_PROFILE_SPECIFIER: 
        TARGET_PATH: Application
        TARGETED_DEVICE_FAMILY: 1

    dependencies:
      - target: Library
      - target: Logic
      - target: Views
      - target: Flow
      - target: Networking
      - carthage: Kingfisher
      - carthage: Overture
      - carthage: KeychainAccess

  Library:
    templates: [Framework]
    info:
      path: Library/Resource/Info.plist
    settings: 
      base: 
        TARGET_PATH: Library
    sources: Library/Source
    dependencies: 
      - carthage: Kingfisher
      - carthage: Overture
      - carthage: KeychainAccess

  Logic:
    templates: [Framework]
    info:
      path: Logic/Resource/Info.plist
    settings: 
      base: 
        TARGET_PATH: Logic
    sources: Logic/Source
    dependencies: 
      - carthage: Kingfisher
      - carthage: Overture
      - carthage: KeychainAccess
      - target: Networking
      - target: Library
      - target: Views
      - target: Flow
      - target: Networking

  Views:
    templates: [Framework]
    info:
      path: Views/Resource/Info.plist
    settings: 
      base: 
        TARGET_PATH: Views
    sources: Views/Source
    dependencies: 
      - target: Library
      - target: Flow
      - carthage: Overture

  Flow:
    templates: [Framework]
    info:
      path: Flow/Resource/Info.plist
    settings: 
      base: 
        TARGET_PATH: Flow
    sources: Flow/Source
    dependencies: 
      - target: Library
      
  Networking:
    templates: [Framework]
    info:
      path: Networking/Resource/Info.plist
    settings: 
      base: 
        TARGET_PATH: Networking
    sources: Networking/Source
    dependencies: 
      - target: Library